// biome-ignore-all lint/performance/noBarrelFile: package-level exports define the public SDK API.
export {
	createVirentBrowserClient,
	type IdentifyResult,
	identify,
	initVirent,
	pageview,
	resetVirent,
	type TrackCustomEventResult,
	type TrackGoalResult,
	type TrackPageviewResult,
	trackEvent,
	trackGoal,
	type VirentBrowserClient,
	type VirentBrowserOptions,
	type VirentCustomEvent,
	type VirentCustomEventInput,
	type VirentEventProperties,
	type VirentGoalInput,
	type VirentGoalPayload,
	type VirentIdentifyInput,
	type VirentIdentifyPayload,
	type VirentJsonValue,
	type VirentPageviewEvent,
	type VirentPageviewInput,
} from "./browser";
